version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamingcafe
    ports:
      - "3307:3306"

  spring-app:
    image: santhil/spe-backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
  reactjs:
    image: santhil/spe-front
    restart: always
    ports:
      - "3000:3000"

volumes:
  mysql-data:
    driver: local